install-local:
	cp passemu.desktop /usr/local/share/applications
	cp vault.svg /usr/share/icons

install:
	cp passemu.desktop /usr/share/applications
	cp vault.svg /usr/share/icons
	chmod +x /usr/share/applications/passemu.desktop
	cp passemu.sh /usr/local/bin
	chmod +x /usr/local/bin/passemu.sh

